# frozen_string_literal: true

guard :rspec, cmd: 'bin/bundle exec spring rspec' do
  require 'guard/rspec/dsl'
  dsl = Guard::RSpec::Dsl.new(self)

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)

  # Rails files
  rails = dsl.rails

  # Run all the tests whenever any application code changes.
  #
  # Since the majority of our tests are in spec/requests/ and don't follow a
  # strict format, there's no obvious way to automatically figure out which
  # individual test to run.
  rails.to_h.each_value do |regex|
    watch(regex) { rspec.spec_dir }
  end
end
